# Testing how well LLM (GPT-4) perform on its own
The codes are the response to a page of textbook/lecture note about some theorems or definitions.

## One qubit computational states and their superposition

In [2]:
import numpy as np

# Computational basis states
ket_0 = np.array([[1], [0]])
ket_1 = np.array([[0], [1]])

# Superposition states
# 1/sqrt(2)
norm_factor = 1 / np.sqrt(2)

# |+> = (|0> + |1>) / sqrt(2)
ket_plus = norm_factor * (ket_0 + ket_1)

# |-> = (|0> - |1>) / sqrt(2)
ket_minus = norm_factor * (ket_0 - ket_1)

# Print them to verify
print("Ket |0>:\n", ket_0)
print("Ket |1>:\n", ket_1)
print("Ket |+>:\n", ket_plus)
print("Ket |->:\n", ket_minus)

Ket |0>:
 [[1]
 [0]]
Ket |1>:
 [[0]
 [1]]
Ket |+>:
 [[0.70710678]
 [0.70710678]]
Ket |->:
 [[ 0.70710678]
 [-0.70710678]]


## One qubit quantum gates

In [3]:
import numpy as np

# Hadamard gate
H = (1/np.sqrt(2)) * np.array([
    [1, 1],
    [1, -1]
])

# Print to verify
print("Hadamard gate:\n", H)

Hadamard gate:
 [[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]


In [4]:
# Computational basis states
ket_0 = np.array([[1], [0]])
ket_1 = np.array([[0], [1]])

# Applying Hadamard to |0> and |1>
H_ket0 = np.dot(H, ket_0)
H_ket1 = np.dot(H, ket_1)

print("H |0> =\n", H_ket0)
print("H |1> =\n", H_ket1)

H |0> =
 [[0.70710678]
 [0.70710678]]
H |1> =
 [[ 0.70710678]
 [-0.70710678]]


## Going beyond one qubit --- Tensor Product of qubit states

In [5]:
import numpy as np

# Single qubit |0>
ket_0 = np.array([[1], [0]])

# Tensor product |0> ⊗ |0>
ket_00 = np.kron(ket_0, ket_0)

print("Tensor product |0⟩ ⊗ |0⟩ = |00⟩ :\n", ket_00)

Tensor product |0⟩ ⊗ |0⟩ = |00⟩ :
 [[1]
 [0]
 [0]
 [0]]


## Bell state

In [6]:
import numpy as np

# Basis vectors
ket_0 = np.array([[1], [0]])
ket_1 = np.array([[0], [1]])

# Tensor products
ket_00 = np.kron(ket_0, ket_0)
ket_11 = np.kron(ket_1, ket_1)

# Bell state (|00> + |11>)/sqrt(2)
bell_phi = (1/np.sqrt(2)) * (ket_00 + ket_11)

print("Bell state |ϕ⟩:\n", bell_phi)

Bell state |ϕ⟩:
 [[0.70710678]
 [0.        ]
 [0.        ]
 [0.70710678]]


## Greenberg-Horne-Zeilinger (GHZ) state

In [7]:
import numpy as np

# Basis vectors
ket_0 = np.array([[1], [0]])
ket_1 = np.array([[0], [1]])

# Tensor products
ket_000 = np.kron(np.kron(ket_0, ket_0), ket_0)
ket_111 = np.kron(np.kron(ket_1, ket_1), ket_1)

# GHZ state
ghz = (1/np.sqrt(2)) * (ket_000 + ket_111)

print("GHZ state |ϕ⟩:\n", ghz)

GHZ state |ϕ⟩:
 [[0.70710678]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.70710678]]


## How to test entanglement?

In [8]:
import numpy as np

# Define |00> and |11>
ket_0 = np.array([[1], [0]])
ket_1 = np.array([[0], [1]])
ket_00 = np.kron(ket_0, ket_0)
ket_11 = np.kron(ket_1, ket_1)

# Bell state (|00> + |11>)/sqrt(2)
bell = (1/np.sqrt(2)) * (ket_00 + ket_11)

# Reshape the 4x1 vector into a 2x2 matrix for SVD
# (First qubit rows, second qubit columns)
bell_matrix = bell.reshape(2, 2)

# Perform SVD
U, S, Vh = np.linalg.svd(bell_matrix)

print("Singular values:", S)

# Count non-zero singular values (Schmidt rank)
schmidt_rank = np.sum(S > 1e-10)

print("Schmidt rank:", schmidt_rank)

if schmidt_rank > 1:
    print("This state is entangled.")
else:
    print("This state is separable.")

Singular values: [0.70710678 0.70710678]
Schmidt rank: 2
This state is entangled.


In [9]:
# Separable |00>
bell = ket_00
bell_matrix = bell.reshape(2, 2)
U, S, Vh = np.linalg.svd(bell_matrix)
print("Singular values:", S)

Singular values: [1. 0.]


## Applying a 1-qubit gate to a multi-qubit state

In [10]:
import numpy as np

# Hadamard gate
H = (1/np.sqrt(2)) * np.array([
    [1, 1],
    [1, -1]
])

# Identity gate
I = np.eye(2)

# Apply H to qubit 0 of 3 qubits:
H_on_first = np.kron(np.kron(H, I), I)

# Print the shape (should be 8x8)
print("H ⊗ I ⊗ I matrix shape:", H_on_first.shape)

H ⊗ I ⊗ I matrix shape: (8, 8)


In [11]:
# |0>
ket_0 = np.array([[1], [0]])

# |000>
ket_000 = np.kron(np.kron(ket_0, ket_0), ket_0)

# Apply (H ⊗ I ⊗ I)
new_state = np.dot(H_on_first, ket_000)

print("New state after applying Hadamard on qubit 0:\n", new_state)

New state after applying Hadamard on qubit 0:
 [[0.70710678]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.70710678]
 [0.        ]
 [0.        ]
 [0.        ]]


## Applying a 2-qubit gate to a multi-qubit state

In [12]:
import numpy as np

# 2-qubit CNOT gate
CNOT = np.array([
    [1,0,0,0],
    [0,1,0,0],
    [0,0,0,1],
    [0,0,1,0]
])

# 1-qubit identity
I = np.eye(2)

# Apply CNOT to qubits 0-1 of 3 qubits: (CNOT ⊗ I)
CNOT_on_first_two = np.kron(CNOT, I)

# Confirm shape (8x8)
print("Shape of (CNOT ⊗ I):", CNOT_on_first_two.shape)

Shape of (CNOT ⊗ I): (8, 8)


In [13]:
# |000>
ket_0 = np.array([[1], [0]])
ket_000 = np.kron(np.kron(ket_0, ket_0), ket_0)

# Apply
new_state = np.dot(CNOT_on_first_two, ket_000)

print("New state:\n", new_state)

New state:
 [[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


## What about applying a CNOT to the 1st and the 3rd qubit?

In [14]:
import numpy as np

# Basic matrices
I = np.eye(2)
X = np.array([[0,1],[1,0]])

# Projectors
P0 = np.array([[1,0],[0,0]])
P1 = np.array([[0,0],[0,1]])

# CNOT with control qubit 0 and target qubit 2 in a 3-qubit register
# U = (P0 ⊗ I ⊗ I) + (P1 ⊗ I ⊗ X)
U = np.kron(P0, np.kron(I, I)) + np.kron(P1, np.kron(I, X))

# Confirm size (8x8)
print("Shape of operator:", U.shape)

# Example: Apply to |000>
ket_0 = np.array([[1],[0]])
ket_000 = np.kron(np.kron(ket_0, ket_0), ket_0)

new_state = np.dot(U, ket_000)

print("New state after applying CNOT(control=0, target=2):\n", new_state)

Shape of operator: (8, 8)
New state after applying CNOT(control=0, target=2):
 [[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


## Last piece --- measurement

In [15]:
import numpy as np

# Projector onto |0>
P0 = np.array([[1,0],
               [0,0]])
I = np.eye(2)

# Example state: GHZ state |000> + |111>
ket_0 = np.array([[1],[0]])
ket_1 = np.array([[0],[1]])

ket_000 = np.kron(np.kron(ket_0, ket_0), ket_0)
ket_111 = np.kron(np.kron(ket_1, ket_1), ket_1)

psi = (1/np.sqrt(2)) * (ket_000 + ket_111)

# Measurement operator projecting qubit 0 to |0>
M0 = np.kron(P0, np.kron(I, I))

# Projected (unnormalized) state
psi_projected = M0 @ psi

# Probability of measuring 0 on qubit 0
prob = np.vdot(psi_projected, psi_projected).real

print("Probability of measuring qubit 0 = 0:", prob)

# If desired, renormalize the projected state
if prob > 0:
    psi_normalized = psi_projected / np.sqrt(prob)
    print("Renormalized post-measurement state:\n", psi_normalized)
else:
    print("Probability is zero, no renormalized state.")

Probability of measuring qubit 0 = 0: 0.4999999999999999
Renormalized post-measurement state:
 [[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
